"""Create Tables Migration

Revision ID: 238f74d8b7ca
Revises: 14cce766fb97
Create Date: 2024-02-03 03:25:48.519129

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '238f74d8b7ca'
down_revision = '14cce766fb97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('ID')
    )
    with op.batch_alter_table('walmart_order_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('groupUserIds', sa.String(length=100), nullable=False))

    with op.batch_alter_table('walmart_order_processed_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walmart_order_id', sa.String(length=50), nullable=False))
        batch_op.alter_column('walmart_order_group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_foreign_key(None, 'walmart_order', ['walmart_order_id'], ['orderID'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walmart_order_processed_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('walmart_order_group_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('walmart_order_id')

    with op.batch_alter_table('walmart_order_groups', schema=None) as batch_op:
        batch_op.drop_column('groupUserIds')

    op.drop_table('users')
    # ### end Alembic commands ###
