"""Create Tables Migration

Revision ID: 91e5fe76a5b6
Revises: c94ee0dd1bde
Create Date: 2023-12-16 16:15:04.607799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '91e5fe76a5b6'
down_revision = 'c94ee0dd1bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walmart_order_processed_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walmart_order_group_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('walmart_order_processed_items_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'walmart_order_groups', ['walmart_order_group_id'], ['ID'])
        batch_op.drop_column('walmart_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('walmart_order_processed_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('walmart_order_id', mysql.VARCHAR(length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('walmart_order_processed_items_ibfk_1', 'walmart_order', ['walmart_order_id'], ['orderID'])
        batch_op.drop_column('walmart_order_group_id')

    # ### end Alembic commands ###
