"""Create Tables Migration

Revision ID: c94ee0dd1bde
Revises: 
Create Date: 2023-12-16 14:10:02.397977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c94ee0dd1bde'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('walmart_order',
    sa.Column('orderID', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('orderID')
    )
    op.create_table('walmart_order_groups',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('walmart_order_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['walmart_order_id'], ['walmart_order.orderID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('walmart_order_processed_items',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('walmart_order_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('per_item_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['walmart_order_id'], ['walmart_order.orderID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('walmart_order_raw_items',
    sa.Column('ID', sa.Integer(), nullable=False),
    sa.Column('walmart_order_id', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('per_item_cost', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['walmart_order_id'], ['walmart_order.orderID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('walmart_order_raw_items')
    op.drop_table('walmart_order_processed_items')
    op.drop_table('walmart_order_groups')
    op.drop_table('walmart_order')
    # ### end Alembic commands ###
